const appname = "Hvar";
const appversion = "Version 1.0.0";
const credits = "Lawrence Devs";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "******";
const forgetPassword = "Forget Password";
const login = "Log in";
const signup = "Sign up";
const createnewAccount = "ro, create a new account";
const loginWith = "Log in with";
const retypePassword = "RetypePassword";
const name = "Name";
const nameHint = "Lawrence Devs";
const privacyPolicy = "Privacy Policy";
const loggedin = "Logged in successfully";
const loggedout = "Logged out successfully";
const termAndCond = "Terms and Conditions";
const alreadyHaveAccount = "Already have an account ? ";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
const searchanything = "Search anything...",
    todayDeal = "Today's Deal",
    flashsale = "Flash Sale",
    topSellers = "Top Sellers",
    brand = "Brand",
    topCategories = "Top Categories",
    womenDress = "Women Dress",
    girlsWatches = "Girls Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    tShirts = "TShirts",
    girlsDress = "Girls Dresses",
    featuredProduct = "Featured Product",
    featuredCategories = "Featured Categories";
const womenClothing = "Women Clothing",
    menClothingFashion = "Men Clothing & Fashion",
    compAccess = "Computer & Accessories",
    automobile = "Automobile",
    kidtoys = "Kids & Toys",
    sports = "Sports",
    jewelery = "jewelery",
    cellPhone = "Cellphone & Tab",
    furniture = "Furniture";
const ghost = "Ghost in the shell",
    cryptonomicon = "Cryptonomicon",
    neuromancer = "Neuromancer",
    akira = "AKIRA",
    lain = "Lain",
    bladeRunner = "Blade Runner";

const video = "Video",
    reviews = "Reviews",
    sellerPolicy = "Seller Policy",
    returnPolicy = "Return Policy",
    supportPolicy = "Support Policy",
    productYouMayLike = "Product you may also like";

const wishlist = "My Wallet", orders = "My Orders", message = "Message";
