// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgxnV_AGydX3z2SNAzpH66qNmyKHvoKs4',
    appId: '1:217519489759:web:1438bbd6fadfbf9b4b1f6a',
    messagingSenderId: '217519489759',
    projectId: 'schoolapp-c2f68',
    authDomain: 'schoolapp-c2f68.firebaseapp.com',
    databaseURL: 'https://schoolapp-c2f68-default-rtdb.firebaseio.com',
    storageBucket: 'schoolapp-c2f68.appspot.com',
    measurementId: 'G-FY9F1P7N00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq7DurJoLYb17Ol5noCoGBoGDP2iqn8Tg',
    appId: '1:217519489759:android:12fbc0e34cebd81b4b1f6a',
    messagingSenderId: '217519489759',
    projectId: 'schoolapp-c2f68',
    databaseURL: 'https://schoolapp-c2f68-default-rtdb.firebaseio.com',
    storageBucket: 'schoolapp-c2f68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhGd9QHp3aTrP8oXQfHmhLnnP3k-11U5w',
    appId: '1:217519489759:ios:a621537e1a2745fc4b1f6a',
    messagingSenderId: '217519489759',
    projectId: 'schoolapp-c2f68',
    databaseURL: 'https://schoolapp-c2f68-default-rtdb.firebaseio.com',
    storageBucket: 'schoolapp-c2f68.appspot.com',
    androidClientId: '217519489759-dmu713fb3ujro1h2ad6umrk31n9bvug9.apps.googleusercontent.com',
    iosClientId: '217519489759-jshf2lui4kq5bkmcack7nji8b1k1puu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhGd9QHp3aTrP8oXQfHmhLnnP3k-11U5w',
    appId: '1:217519489759:ios:f0a6614d7edddaf24b1f6a',
    messagingSenderId: '217519489759',
    projectId: 'schoolapp-c2f68',
    databaseURL: 'https://schoolapp-c2f68-default-rtdb.firebaseio.com',
    storageBucket: 'schoolapp-c2f68.appspot.com',
    androidClientId: '217519489759-dmu713fb3ujro1h2ad6umrk31n9bvug9.apps.googleusercontent.com',
    iosClientId: '217519489759-4o7nbrbtmdusqvoomt776aj4i84g24vn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
